### ISSUE TITLE
Can't ignore imported files

### ISSUE THREAD

**Issue by tassoevan** [bcremer/sculpin-less-bundle#1]
I usually split my *.less files, importing everything in a single file. I just want that file parsed as *.css, not all the imported ones. Is this possible?

**Comment by bcremer** [comment]
The underlying LESS implementation (https://github.com/oyejorge/less.php) is capable of that.

At the moment a simple extension whitelist is used (see: https://github.com/bcremer/sculpin-less-bundle/blob/master/LessConverter.php#L47).

This whitelist could be extended to a per file whitelist.

If one would like to implement that a new configuration node has to be added here
https://github.com/bcremer/sculpin-less-bundle/blob/master/DependencyInjection/Configuration.php#L19
and here https://github.com/bcremer/sculpin-less-bundle/blob/master/DependencyInjection/SculpinLessExtension.php#L23.

The actual filtering could be done here: https://github.com/bcremer/sculpin-less-bundle/blob/master/LessConverter.php#L47.

So it's possible to implement but it is not (yet).

Feel free to submit a pull request :)

**Comment by bcremer** [comment]
Should be implemented now. Example usage: https://github.com/shopware/devdocs/commit/64a3b68fb43e2e5cf1ace9b7cfacba8542dd6419
